import { Geist, Geist_Mono } from "next/font/google";
import { VT323 } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const vt323 = VT323({
  weight: "400",
  variable: "--font-vt323",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${vt323.variable} ${geistSans.variable} ${geistMono.variable} font-vt323 antialiased relative`}
      >
        {/* 🔹 NOISE BACKGROUND */}
        <div className="noise-background-fixed pointer-events-none" />
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
